### ISSUE TITLE
How can I install it 

### ISSUE THREAD

**Issue by aelam** [RLovelett/langserver-swift#11]
I can't find installation instruction in README ?
Could you please add one

**Comment by RLovelett** [comment]
Well the [Build](https://github.com/RLovelett/langserver-swift#build) instructions should cover 90% of the problem.

```
swift build -Xswiftc -target -Xswiftc x86_64-apple-macosx10.11 -c release
```

That should make the actual executable program and place it inside, `.build/release/LanguageServer`. Up until here we're just using the Swift Package Manager and its process. If you want to change/configure that stuff then you'll want to look there for more information.

After you have the executable though it's really kind of up to you where you "install" it. I would think you'd want to put in on your `PATH` somewhere but without knowing how you plan to use it I'm not sure where to say to install it.

If you are using it with [vscode-swift](https://github.com/RLovelett/vscode-swift) it is going to expect to find the executable you built above at [`/usr/local/bin/LanguageServer`](https://github.com/RLovelett/vscode-swift/blob/03a01df67a3593456cdcc398a29236aa4331c9a3/package.json#L54). Though even that location is configurable so really you can "install" it anywhere you like.

**Comment by aelam** [comment]
Thanks man! It's my first time to hear the LanguageServer, SourceKit, SourceKitten when I'm trying something new (to me) ... 
I appreciate your 90% of the answer here  -__-. 
It would be better append the answer to README. since it still takes time to understand after struggled to install it.

**Comment by aelam** [comment]
By the way. is LanguageServer available in homebrew ?

**Comment by RLovelett** [comment]
I can appreciate that it is difficult. Please be patient as it is still early days in this whole thing. I think as the Swift eco-system matures so will this process.

It is not available in Homebrew. It is just one more thing to have to maintain at this point and frankly is a burden of work I'm not ready to take on.  That is until this tool and the tooling around it matures a little bit more.
