### ISSUE TITLE
Cannot compile release

### ISSUE THREAD

**Issue by RLovelett** [RLovelett/langserver-swift#15]
Running `swift build -Xswiftc -target -Xswiftc x86_64-apple-macosx10.11 -c release` fails to compile on `master`.

I've reported this to [bugs.swift.org as SR-4253](https://bugs.swift.org/browse/SR-4253). Unfortunately until either a fix or a work-around is found no release can currently be made.

Created an issue here to track it as well.

**Comment by johndpope** [comment]
presumably resolved.

**Comment by RLovelett** [comment]
Yes it is! Thanks @johndpope 👍

It makes our requirement be for Swift 3.1.1 because that is the release that includes the fix for SR-4253.

I'll leave this open until I update the README. Thanks for mentioning it.
