### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by johndpope** [RLovelett/langserver-swift#20]
steps to reproduce

clone repo
swift build -Xswiftc -target -Xswiftc x86_64-apple-macosx10.11
cp ./.build/debug/LanguageServer /usr/local/bin/LanguageServer

load vscode 
open swift file
https://gist.github.com/johndpope/938bbe540d3f9e1dd626cc4e59392542

<img width="1393" alt="screen shot 2017-05-09 at 1 37 45 pm" src="https://cloud.githubusercontent.com/assets/289994/25864252/c5aedb44-34bc-11e7-9fd0-34739e1e8278.png">

**Comment by RLovelett** [comment]
Where you able to use the steps you found in [this comment](https://github.com/RLovelett/vscode-swift/issues/27#issuecomment-281686033) to track down this bug?
