### ISSUE TITLE
enhancement - log tracking / reconn

### ISSUE THREAD

**Issue by johndpope** [RLovelett/langserver-swift#21]
I was reviewing the official golang project and some log tracking caught my eye.
You may consider cherry picking to catch bugs.

Go Language Server (Experimental)
<img width="995" alt="screen shot 2017-05-15 at 21 19 51" src="https://cloud.githubusercontent.com/assets/289994/26085735/40032016-39b4-11e7-8fe3-a2f1d6326091.png">

To collect traces, set **"go.languageServerFlags": ["-trace"]**
To collect errors from language server in a logfile, set **"go.languageServerFlags": ["-trace", "-logfile", "path to a text file that exists" ]**

<img width="1286" alt="screen shot 2017-05-15 at 21 24 18" src="https://cloud.githubusercontent.com/assets/289994/26085814/d5f603f4-39b4-11e7-9f23-eb1d61881add.png">

Pretty nice - it exposes the ability to execute methods of go code.

<img width="1008" alt="screen shot 2017-05-15 at 21 25 38" src="https://cloud.githubusercontent.com/assets/289994/26085843/047ebd9c-39b5-11e7-96bf-73c75175b483.png">

**Comment by RLovelett** [comment]
This project does not make use of the go language server. So I'm not sure how this is applicable. I'm going to close this as I'm not really sure what to do with this.

**Comment by johndpope** [comment]
consider that langserver-swift should log stuff - and if it does already - there should be a debug flag to turn on and configure.

**Comment by johndpope** [comment]
the intention being - if (and when) the langserver breaks - people can help report back the errors with logs and community can help - as opposed to it being a black box and it being a - fix it yourself scenario.
